# Generated by Django 4.2.7 on 2023-12-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="comprar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("correo_electronico", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=100)),
                ("dirrecion", models.CharField(max_length=100)),
                ("numero_de_tarjeta", models.CharField(max_length=100)),
                ("fecha_de_expedicion", models.CharField(max_length=100)),
                ("ccv", models.CharField(max_length=100)),
            ],
        ),
    ]
