# Generated by Django 4.2.7 on 2023-12-06 04:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pagina", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comprar",
            old_name="dirrecion",
            new_name="direccion",
        ),
    ]
