# Generated by Django 4.2.7 on 2023-12-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina", "0002_rename_dirrecion_comprar_direccion"),
    ]

    operations = [
        migrations.CreateModel(
            name="sugerencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("correo_electronico", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=100)),
                ("mensaje", models.CharField(max_length=500)),
            ],
        ),
    ]
