# Generated by Django 4.2.8 on 2024-03-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pagina", "0004_historial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="historial",
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name="usuario_historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "historial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagina.historial",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
