# Generated by Django 4.2.8 on 2024-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina", "0005_alter_historial_historial_usuario_historial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="fecha",
            field=models.DateField(auto_now=True),
        ),
    ]
