# Generated by Django 4.2.8 on 2024-03-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina", "0006_alter_historial_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
