# Generated by Django 4.2.8 on 2024-03-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina", "0009_alter_historial_id_usuario_historial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="fecha",
            field=models.DateTimeField(),
        ),
    ]
