# Generated by Django 4.2.8 on 2024-03-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagina", "0010_alter_historial_fecha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historial",
            name="historial",
        ),
        migrations.AddField(
            model_name="historial",
            name="busqueda",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
